In [246]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np
from sqlalchemy import create_engine
import psycopg2 as psy

In [247]:
df=pd.read_csv('C:\\Users\\muril\\OneDrive\\Área de Trabalho\\Projeto-Preparação\\data\\dynamic_supply_chain_logistics_dataset.csv')
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 32065 entries, 0 to 32064
Data columns (total 26 columns):
 #   Column                           Non-Null Count  Dtype
---  ------                           --------------  -----
 0   timestamp                        32065 non-null  str
 1   vehicle_gps_latitude             32065 non-null  float64
 2   vehicle_gps_longitude            32065 non-null  float64
 3   fuel_consumption_rate            32065 non-null  float64
 4   eta_variation_hours              32065 non-null  float64
 5   traffic_congestion_level         32065 non-null  float64
 6   warehouse_inventory_level        32065 non-null  float64
 7   loading_unloading_time           32065 non-null  float64
 8   handling_equipment_availability  32065 non-null  float64
 9   order_fulfillment_status         32065 non-null  float64
 10  weather_condition_severity       32065 non-null  float64
 11  port_congestion_level            32065 non-null  float64
 12  shipping_costs                   32065 non-null  float64
 13  supplier_reliability_score       32065 non-null  float64
 14  lead_time_days                   32065 non-null  float64
 15  historical_demand                32065 non-null  float64
 16  iot_temperature                  32065 non-null  float64
 17  cargo_condition_status           32065 non-null  float64
 18  route_risk_level                 32065 non-null  float64
 19  customs_clearance_time           32065 non-null  float64
 20  driver_behavior_score            32065 non-null  float64
 21  fatigue_monitoring_score         32065 non-null  float64
 22  disruption_likelihood_score      32065 non-null  float64
 23  delay_probability                32065 non-null  float64
 24  risk_classification              32065 non-null  str
 25  delivery_time_deviation          32065 non-null  float64
dtypes: float64(24), str(2)
memory usage: 6.4 MB

In [248]:
df.head()

,timestamp,vehicle_gps_latitude,vehicle_gps_longitude,fuel_consumption_rate,eta_variation_hours,traffic_congestion_level,warehouse_inventory_level,loading_unloading_time,handling_equipment_availability,order_fulfillment_status,...,iot_temperature,cargo_condition_status,route_risk_level,customs_clearance_time,driver_behavior_score,fatigue_monitoring_score,disruption_likelihood_score,delay_probability,risk_classification,delivery_time_deviation
0,2021-01-01 00:00:00,40.375568,-77.014318,5.136512,4.998009,5.927586,985.716862,4.951392,0.481294,0.761166,...,0.574400,0.777263,1.182116,0.502006,0.033843,0.978599,0.506152,0.885291,Moderate Risk,9.110682
1,2021-01-01 01:00:00,33.507818,-117.036902,5.101512,0.984929,1.591992,396.700206,1.030379,0.620780,0.196594,...,-9.753493,0.091839,9.611988,0.966774,0.201725,0.918586,0.980784,0.544178,High Risk,8.175281
2,2021-01-01 02:00:00,30.020640,-75.269224,5.090803,4.972665,8.787765,832.408935,4.220229,0.810933,0.152742,...,-6.491034,0.253529,6.570431,0.945627,0.264045,0.394215,0.998633,0.803322,High Risk,1.283594
3,2021-01-01 03:00:00,36.649223,-70.190529,8.219558,3.095064,0.045257,0.573283,0.530186,0.008525,0.811885,...,-0.151276,0.877576,0.548952,4.674035,0.362885,0.905444,0.993320,0.025977,High Risk,9.304897
4,2021-01-01 04:00:00,30.001279,-70.012195,5.000075,3.216077,8.004851,914.925067,3.620890,0.020083,0.053659,...,2.429448,0.262081,8.861443,3.445429,0.016957,0.258702,0.912433,0.991122,High Risk,7.752484

In [249]:
df['timestamp']=pd.to_datetime(df['timestamp'])

In [250]:
df['date']=pd.to_datetime(df['timestamp']).dt.date
df['hour']=pd.to_datetime(df['timestamp']).dt.time
df.drop('timestamp',axis=1,inplace=True)
df = df.iloc[:, ::-1]#inverter a ordem das colunas
df.head()

,hour,date,delivery_time_deviation,risk_classification,delay_probability,disruption_likelihood_score,fatigue_monitoring_score,driver_behavior_score,customs_clearance_time,route_risk_level,...,weather_condition_severity,order_fulfillment_status,handling_equipment_availability,loading_unloading_time,warehouse_inventory_level,traffic_congestion_level,eta_variation_hours,fuel_consumption_rate,vehicle_gps_longitude,vehicle_gps_latitude
0,00:00:00,2021-01-01,9.110682,Moderate Risk,0.885291,0.506152,0.978599,0.033843,0.502006,1.182116,...,0.359066,0.761166,0.481294,4.951392,985.716862,5.927586,4.998009,5.136512,-77.014318,40.375568
1,01:00:00,2021-01-01,8.175281,High Risk,0.544178,0.980784,0.918586,0.201725,0.966774,9.611988,...,0.230660,0.196594,0.620780,1.030379,396.700206,1.591992,0.984929,5.101512,-117.036902,33.507818
2,02:00:00,2021-01-01,1.283594,High Risk,0.803322,0.998633,0.394215,0.264045,0.945627,6.570431,...,0.027210,0.152742,0.810933,4.220229,832.408935,8.787765,4.972665,5.090803,-75.269224,30.020640
3,03:00:00,2021-01-01,9.304897,High Risk,0.025977,0.993320,0.905444,0.362885,4.674035,0.548952,...,0.616619,0.811885,0.008525,0.530186,0.573283,0.045257,3.095064,8.219558,-70.190529,36.649223
4,04:00:00,2021-01-01,7.752484,High Risk,0.991122,0.912433,0.258702,0.016957,3.445429,8.861443,...,0.952385,0.053659,0.020083,3.620890,914.925067,8.004851,3.216077,5.000075,-70.012195,30.001279

In [251]:
df.isna().sum()

hour                               0
date                               0
delivery_time_deviation            0
risk_classification                0
delay_probability                  0
disruption_likelihood_score        0
fatigue_monitoring_score           0
driver_behavior_score              0
customs_clearance_time             0
route_risk_level                   0
cargo_condition_status             0
iot_temperature                    0
historical_demand                  0
lead_time_days                     0
supplier_reliability_score         0
shipping_costs                     0
port_congestion_level              0
weather_condition_severity         0
order_fulfillment_status           0
handling_equipment_availability    0
loading_unloading_time             0
warehouse_inventory_level          0
traffic_congestion_level           0
eta_variation_hours                0
fuel_consumption_rate              0
vehicle_gps_longitude              0
vehicle_gps_latitude               0
dtype: int64

In [252]:
df.duplicated().sum()

np.int64(0)

In [253]:
for col in df.columns:
    if df[col].dtype in ['int64', 'float64']:
        maximo=df[col].max()
        minimo=df[col].min()
        media=df[col].mean()
        print(f'Coluna: {col}')
        print(f'Máximo: {maximo:.2f}')
        print(f'Mínimo: {minimo:.2f}')
        print(f'Média: {media:.2f}')
        print('---')

Coluna: delivery_time_deviation
Máximo: 10.00
Mínimo: -2.00
Média: 5.18
---
Coluna: delay_probability
Máximo: 1.00
Mínimo: 0.00
Média: 0.70
---
Coluna: disruption_likelihood_score
Máximo: 1.00
Mínimo: 0.00
Média: 0.80
---
Coluna: fatigue_monitoring_score
Máximo: 1.00
Mínimo: 0.00
Média: 0.60
---
Coluna: driver_behavior_score
Máximo: 1.00
Mínimo: 0.00
Média: 0.50
---
Coluna: customs_clearance_time
Máximo: 5.00
Mínimo: 0.50
Média: 2.30
---
Coluna: route_risk_level
Máximo: 10.00
Mínimo: 0.00
Média: 7.00
---
Coluna: cargo_condition_status
Máximo: 1.00
Mínimo: 0.00
Média: 0.30
---
Coluna: iot_temperature
Máximo: 40.00
Mínimo: -10.00
Média: 0.04
---
Coluna: historical_demand
Máximo: 10000.00
Mínimo: 100.00
Média: 6022.00
---
Coluna: lead_time_days
Máximo: 15.00
Mínimo: 1.00
Média: 5.23
---
Coluna: supplier_reliability_score
Máximo: 1.00
Mínimo: 0.00
Média: 0.50
---
Coluna: shipping_costs
Máximo: 1000.00
Mínimo: 100.00
Média: 459.37
---
Coluna: port_congestion_level
Máximo: 10.00
Mínimo: 0.00
Média: 6.98
---
Coluna: weather_condition_severity
Máximo: 1.00
Mínimo: 0.00
Média: 0.50
---
Coluna: order_fulfillment_status
Máximo: 1.00
Mínimo: 0.00
Média: 0.60
---
Coluna: handling_equipment_availability
Máximo: 1.00
Mínimo: 0.00
Média: 0.30
---
Coluna: loading_unloading_time
Máximo: 5.00
Mínimo: 0.50
Média: 2.29
---
Coluna: warehouse_inventory_level
Máximo: 1000.00
Mínimo: 0.00
Média: 299.25
---
Coluna: traffic_congestion_level
Máximo: 10.00
Mínimo: 0.00
Média: 4.99
---
Coluna: eta_variation_hours
Máximo: 5.00
Mínimo: -2.00
Média: 2.89
---
Coluna: fuel_consumption_rate
Máximo: 20.00
Mínimo: 5.00
Média: 8.01
---
Coluna: vehicle_gps_longitude
Máximo: -70.00
Mínimo: -120.00
Média: -90.12
---
Coluna: vehicle_gps_latitude
Máximo: 50.00
Mínimo: 30.00
Média: 38.02
---

In [254]:
df['risk_classification'].unique()

<StringArray>
['Moderate Risk', 'High Risk', 'Low Risk']
Length: 3, dtype: str

In [255]:
df['risk_classification']=df['risk_classification'].str.replace(' ', '_')
df['risk_classification'].unique()

<StringArray>
['Moderate_Risk', 'High_Risk', 'Low_Risk']
Length: 3, dtype: str

In [256]:
#df.to_csv('supply_chain_clean', index=False, encoding='utf-8')

In [257]:
df_EDA=pd.read_csv('\\Users\\muril\\OneDrive\\Área de Trabalho\\Projeto-Preparação\\data\\supply_chain_clean.csv')
df_EDA.head()

,hour,date,delivery_time_deviation,risk_classification,delay_probability,disruption_likelihood_score,fatigue_monitoring_score,driver_behavior_score,customs_clearance_time,route_risk_level,...,weather_condition_severity,order_fulfillment_status,handling_equipment_availability,loading_unloading_time,warehouse_inventory_level,traffic_congestion_level,eta_variation_hours,fuel_consumption_rate,vehicle_gps_longitude,vehicle_gps_latitude
0,00:00:00,2021-01-01,9.110682,Moderate_Risk,0.885291,0.506152,0.978599,0.033843,0.502006,1.182116,...,0.359066,0.761166,0.481294,4.951392,985.716862,5.927586,4.998009,5.136512,-77.014318,40.375568
1,01:00:00,2021-01-01,8.175281,High_Risk,0.544178,0.980784,0.918586,0.201725,0.966774,9.611988,...,0.230660,0.196594,0.620780,1.030379,396.700206,1.591992,0.984929,5.101512,-117.036902,33.507818
2,02:00:00,2021-01-01,1.283594,High_Risk,0.803322,0.998633,0.394215,0.264045,0.945627,6.570431,...,0.027210,0.152742,0.810933,4.220229,832.408935,8.787765,4.972665,5.090803,-75.269224,30.020640
3,03:00:00,2021-01-01,9.304897,High_Risk,0.025977,0.993320,0.905444,0.362885,4.674035,0.548952,...,0.616619,0.811885,0.008525,0.530186,0.573283,0.045257,3.095064,8.219558,-70.190529,36.649223
4,04:00:00,2021-01-01,7.752484,High_Risk,0.991122,0.912433,0.258702,0.016957,3.445429,8.861443,...,0.952385,0.053659,0.020083,3.620890,914.925067,8.004851,3.216077,5.000075,-70.012195,30.001279

In [258]:
engine = create_engine('postgresql://postgres:722406@localhost:5432/SupplyChain')
df.to_sql(name='SupplyChain', con = engine, if_exists='replace',index = False, chunksize=1000)

32065